### ISSUE TITLE
Enhancement: Client-side redirecting to a login page when timeout is hit

### ISSUE THREAD

**Issue by scole96** [lindleycb/meteor-stale-session#4]
I'm testing the use of this package (which seems to be just what my security group wants us to have - thanks!) but when the session is purged from the server the client doesn't seem to know about it and allows the user to continue using the app until it makes a call to the server to do something and then most of the time it just appears to hang (at least to a user). I was thinking about enhancing the client.js so that it kept track of the last activity and when the client hit the timeout threshold it redirected the browser to the login page. I know this could be overridden by js on the client, but I don't care about playing nice with hackers, but for regular users when the timeout was hit they would be back at the login page. An additional enhancement might be to put up a warning a minute or two before to prompt them to do something so the timeout is extended.
Thoughts? 
thanks,
stephen

**Comment by butlera1** [comment]
Hi Chris,

I also have the problem that my client is not being notified. I'm using iron-router and I've reduced the router.js to just the following (see below). I used your source code locally in my build and added a printout when the timeout happens so I can easily see when the server portion times out and deletes the login token. The issue is the client side does not get notified or execute any code to let the user know.

Any thoughts?

--Arch
 

```javascript
Router.route("/", function () {
    console.log("MAIN");

    if (Meteor.userId()) {
      this.render("navigationBar");
    }else{
      this.render("navigationBar");
    }
  });

```

**Comment by butlera1** [comment]
Hi, Chris,
I should add that I've tested this with Chrome, FF, and Safari and they all exhibit the same behavior.

--Arch

**Comment by AdamBrodzinski** [comment]
@butlera1 I think this is the intended behavior. On my tests, once the session times out the client has no idea that it's been logged out, which makes it confusing to the user as they still think they're logged in, but Meteor methods and publications will fail. 

I'll be making a fork/PR soon with this functionality, as well as a 1min warning callback so you can display a notification. 

cc @lindleycb

**Comment by lindleycb** [comment]
Hi guys, yes this package was written way back as a simple "kill the session after a period of inactivity" security requirement for one of my projects.  The focus was more on security than user experience.  I'm happy to see it enhanced.  A quick google turned up the following though which might help with client callbacks on logout:
 *   https://github.com/gwendall/meteor-auth-client-callbacks
 *   https://github.com/mizzao/meteor-user-status
 *   https://atmospherejs.com/differential/event-hooks

**Comment by butlera1** [comment]
Hi, Chris.

These packages you've listed rely on Meteor.userId() being reactive when the user is timed out by the stale-session package. I don't believe Meteor.userId() is reactive when a user is timed out though. 

The following code is not working when the user is timed out by stale-session in my application but it does work correctly when the user actively logs out (I'm using Meteor's accounts-base, accounts-password, and ian:accounts-ui-bootstrap-3 packages).

```javascript
  Deps.autorun(function () {
    if (Meteor.userId()) {
      console.log("user has logged in....")
    } else {
      console.log("user has logged out....")
    }
  });
```

Calling the Client-only Meteor.logout() function when timing a user out would seem appropriate. I'm not sure how to do this from the server side where the timing out code is running.

--Arch

**Comment by AdamBrodzinski** [comment]
@butlera1 I should have a solution working tomorrow. I'll keep you posted.

**Comment by AdamBrodzinski** [comment]
@butlera1 I think I may have found out something... at least for my use case. This solution doesn't add the 1min warning callback or a callback on logout, but it does enable the UI to update when the token is wiped out.

I published an extra field but instead of using a null subscription I made a `'userInfo'` publication and it made the UI not update when the token is wiped. However if I change this to a null token (or comment out the pub) then the UI will instantly update to logged out.

The most simple test that works for me (albeit fires any time user is logged out)

```javascript
Meteor.startup(function() {

  Deps.autorun(function() {
    if (!Meteor.userId()) {
      Router.go('/logged-out-security');
    }
  });

});
```

Here's a simple use case (I can post the spike repo if it helps) that
allows access and then as soon as the user is timed out of the secure
page it redirects to logged out notice page. This also uses an app controller
that the SecretsController inherits from so I don't have to dup. the code.


```javascript

AppController = RouteController.extend({

 authorizeRoles: function(role) {
    if (!Meteor.userId()) {
      // redirect to "you've been logged out"
      return Router.go("/logged-out-security");
    } else if (User.isInRole('admin')) {
       // allow access to page
      return console.debug('Auth Granted: Admin');
    } else {
      // redirect to a no access page
      return Router.go('/no-access');
    }    
  }, 
 
});



// page for a list of Secrets - /secrets
SecretsController.Index = AppController.extend({
  template: 'secretIndex',

  onBeforeAction: function() {  
    // enforces access and redirects on timeout
    this.authorizeRoles('admin');
    this.next();
  }
});

```

**Comment by butlera1** [comment]
Cool, Adam. Can you show me the code where you...

>I published an extra user field but instead of using a null subscription I made a 'userInfo' publication and it made the UI not update when the token is wiped. However if I change this to a null token (or comment out the user publication) then the UI will instantly update to logged out when the stale session was removed.

Thanks.

--Arch

**Comment by butlera1** [comment]
Hey, Adam, any luck on this?

�Arch

**Comment by AdamBrodzinski** [comment]
@butlera1 I showed my client and they also wanted the 1min warning before logging off so i'm going to start on that tomorrow. It'll prob. be a fork as it seems like i'll have to poll differently than this package. Keep an eye out on my GH fork and i'll post back here when there's something ready (within this week for sure). 

Did you still need the code example for the user publish? I just saw that. Basically I was doing something like:

```
Meteor.publish("userInfo", function(userId){
  return Meteor.users.findOne(id, some extra info selector...);
});
``

but it should have used null instead

```
Meteor.publish(null, function(userId){
  return Meteor.users.findOne(id, some extra info selector...);
});
``

That allowed the UI to update instantly using this package (or even disabling the publish would do it too).

**Comment by AdamBrodzinski** [comment]
@butlera1 I've finished a solution that adds a warning and expired session callback. I still have to update the readme, and create an example reproduction for the PR.

These work by setting up a different interval on the client and then it measures the time that's passed since the last event (also now this is throttled to prevent thrashing on low end devices). The server side is still handled by the original code so if the client closes the browser they're logged off like before.

Now you can setup callbacks like:

```js
  Meteor.onStaleSessionExpired = function() {
    log("Expired cb fired");
    Router.go("/timed-out");
  };

  Meteor.onStaleSessionWarning = function() {
    log("Warning cb fired");
   // don't fire an alert here or it locks up the UI
    sweetAlert("Are you still there?",
       "You're about to be logged off, click ok to stay logged in.", "warning");
  };    

```

https://github.com/AdamBrodzinski/meteor-stale-session/blob/feature-callbacks/client.js

Hoping to have a PR ready in a few days but thought i'd post this in case you're waiting on something for a project.

Cheers!
Adam

**Comment by butlera1** [comment]
Thanks, Adam. Works great.

I�m curious on something which I have not dug into. From your previous correspondence you noted:

I published an extra field but instead of using a null subscription I made a 'userInfo' publication and it made the UI not update when the token is wiped. However if I change this to a null token (or comment out the pub) then the UI will instantly update to logged out.

The most simple test that works for me (albeit fires any time user is logged out)

Meteor.startup(function() {

  Deps.autorun(function() {
    if (!Meteor.userId()) {
      Router.go('/logged-out-security');
    }
  });

});

In my application, I�m publishing Meteor.user and so I�m unable to get any Deps.autorun to fire correctly based on the reactivity of Meteor.userId() or Meteor.user().

This seems to me to be a bug. Why would publishing anything from the Meteor.users collection cause the reactivity of Meteor.userId() to be removed/nullified?

�Arch

**Comment by AdamBrodzinski** [comment]
@butlera1 , There may be an issue with the clientside fork above... I was having issues with it logging you off as soon as you log in (intermittently)... not sure what the issue is but am planning to look at it closer in the next few days (also let me know if you found it already!). I'm thinking it might be a value caught in a closure or something? Should know soon.

**Comment by butlera1** [comment]
Thanks for the heads up. I have not seen any issues.

�Arch

**Comment by shivamarora123** [comment]
> ```js
> Meteor.onStaleSessionExpired = function() {
>     log("Expired cb fired");
>     Router.go("/timed-out");
>   };
> ```

Hi @AdamBrodzinski  Where should i place this code?

**Comment by AdamBrodzinski** [comment]
@shivamarora123 sorry, i'm not sure. I haven't really used this in years.

**Comment by shivamarora123** [comment]
@AdamBrodzinski  I am having the same issue which mentioned earlier ..Stale sessions deletes the token from server but client is not aware of the token deletion and application is stuck..and i tried applied this code but no action is performed...
See, if you can help..Thanks :)

Meteor.onStaleSessionExpired = function() {
    log("Expired cb fired");
    Router.go("/timed-out");
  };
